# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: training001
  tag: v1.0.0
  pullPolicy: IfNotPresent
service:
  name: Node
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
services:
